name: climaax_heavy_rainfall

channels:
    - conda-forge

dependencies:
    - cartopy=0.23.0
    - cdsapi=0.7.0
    - contextily=1.6.0
    - dask=2024.7.0
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.1
    - numpy=1.26.4
    - osmnx=1.9.3
    - pandas=2.2.2
    - pip
    - plotly=5.22.0
    - pooch=1.8.2
    - pyproj=3.6.1
    - python-kaleido=0.2.1
    - python=3.11
    - rasterio=1.3.10
    - rioxarray=0.15.7
    - rio-cogeo=5.3.3
    - scipy=1.14.0
    - shapely=2.0.4
    - xarray=2024.6.0

