name: climaax_extreme_precipitation

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - pip
        - jupyterlab
        - netCDF4
        - dask
        - xarray
        - rioxarray
        - cartopy
        - scipy
        - rasterio
        - numpy
        - cdsapi
        - plotly
        - contextily
        - geopandas
        - osmnx
        - pip:
            - damagescanner
            - jupyterlab_myst
            - shapely
            - rio-cogeo
